>>> print("where's my output?")
Not my output

Here's an exception happening:

>>> raise Exception('boom!')
